<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        // param callback
        const get = (url) => {

            return new Promise((resolve,reject)=>{
                const xhr = new window.XMLHttpRequest()
    
                xhr.onreadystatechange = () => {
                    if(xhr.readyState === 4)
                    {
                        if(xhr.status === 200)
                        {
                            // console.log('terminé')
                            resolve(xhr.responseText)
                        }else{
                            reject(xhr)
                        }
                    }
                }
                xhr.open('GET',url,true)
                xhr.send()
            })
        }

       
        
        // ici on peut utiliser try catch pour récupèrer les erreurs 
        const getPosts = async () => {
            try{
                var response = await get('https://jsonplaceholder.typicode.com/users')
                const users = JSON.parse(response)
                response = await get('https://jsonplaceholder.typicode.com/comments?userId='+users[0].id)
                const posts = JSON.parse(response)
                console.log(posts) 
            }catch(error)
            {
                console.log('Il y a eu un problème', error)
            }
        }

       
        getPosts()
    
        
        /* https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Statements/async_function */
    
    </script>


</body>
</html>